# Generated by Django 2.2.7 on 2019-11-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_systemmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemMessage',
        ),
    ]
